### ISSUE TITLE
Fix predict occultation form period buttons.

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#656]
O botão de 6 meses não está funcioanando como esperado,  
testei usando data inicial 01/05/2023 esperava data final 31/10/2023 mas o resultado foi 28/10/2023 
parece estar multiplicando a qtd de dias usando 30.  não sei se é assim que está implemenato, mas tem uma função do javascript que retorna o ultimo dia do mes sem precisar fazer conta se não me engano é na bliblioteca moment.

**Comment by rcboufleur** [comment]
Validado
