### ISSUE TITLE
Dashboard Occultation UI tweaks

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#658]
Alteração dos textos conforme  reunião dia 28/04 descrito no documento: [notas de reunião](https://docs.google.com/document/d/10JQWmbBPOy2yht5bbbbGhP10G8ny5HUFwYbqOv_llTY/edit
)

**Card de Filtros:**
- [x] Alterar o Titulo do card Occultation Filter → Selection of occultation events
- [x] Adicionar um icone de filtro no titulo do card. 
- [x] Date Start -> Initial Date
- [x] Date End -> Final Date
- [x] Filter Type  Values: 
- Name → Object name
- DynClass → Dynamic class (with subclasses)
- Base DynClass → Dynamic class

- [x] Alterar o campo Magnitude
- Label: Magnitude
- Deve ser um campo do tipo range
- valor minimo 9.0 
- valor maximo ?  definir com o time de ciencia. 
- valor default 9.0 - 18.0  (pelo menos foi o exemplo utilizado, definir com o time de ciencia)
- no banco de dados salvar como um campo string com os valores valores float separados por ';' exemplo:  "9.0;18.00"

- [x] Alterar o campo Diametro
- Label: Diameter (Km.)
- Deve ser um campo do tipo range
- valor minimo ? definir com o time de ciencia. 
- valor maximo ?  definir com o time de ciencia. 
- valor default ? definir com o time de ciencia. 
- no banco de dados salvar como um campo string com os valores valores inteiros separados por ';' exemplo:  "100;200" (acredito que não compense utilizar float neste campo)

**Lista de Occultações:**

- [ ] Adicionar todas as colunas disponiveis mas, levantar com time de ciencias quais são as prioritarias e deixar as demais ocultas por padrão. 
- [ ] Todas as colunas devem ser ordenaveis se possivel, as que não puderem deixar a ordenação desabilitada.

**Comment by vmattoscarvalho** [comment]
obs: onde está solicitando "no banco de dados salvar... " foi ignorado uma vez que essa tela somente consulta e não salva dados no banco

**Comment by glaubervila** [comment]
Validado.
