### ISSUE TITLE
Integração com SORA - to generate maps

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#668]

**Comment by glaubervila** [comment]
Adicionei o serviço do SORA ao ambiente do TNO. 
Mas não levei para o ambiente de dev por que a imagem do SORA está rodando como root. é um requisito que as imagens em produção não rodem como root. cada serviço roda com um usuario especifico por questões de permissões. 

Solicitei ao Mozar que altere a imagem para rodar sem root. 

Como exemplo deixo o dockerfile do backend do TNO:  [dockerfile](https://github.com/linea-it/tno/blob/11Tech/backend/Dockerfile#L37)

e no docker-compose do TNO será adicionado o seguinte trecho: 
`
  sora:
    image: mozaru/carto-sora
    user: "1000:1000"
    environment:
      INPUT_PATH: "/media/input"
      OUTPUT_PATH: "/media/output"
      CACHE_PATH: "/media/output"
      PORT: 8000
    volumes:
      - ./archive/sora/input:/media/input
      - ./archive/sora/output:/media/output
    command: python3.7 /opt/server/main.py
`

**Atenção** ao parametro user que é obrigatório no ambiente real.

e no Ngnix será adicionado uma nova rota /sora

`
    location /sora/ {
        proxy_pass http://sora:8000/
    }
`

Essas mudanças já estão no branch feat/add_sora_service

**Comment by rcboufleur** [comment]
Para gerar mapas com as informações da tabela de predição:

```python
from sora.prediction.occmap import plot_occ_map as occmap
occmap(name, radius, coord, time, ca, pa, vel, dist, mag=mag, longi=longi, dpi=50,  nameimg='image_filename', path='path/to/save/file/', fmt='jpg')
```

name -> Nome do objeto conforme aparece na coluna Object da tabela: **name** (**number**), formato str
radius -> Raio do objeto, valor da coluna **diameter** da tabela dividido por dois e 0 se não existir, formato float
coord -> String formada pelos campos '**ra_star_candidate** **dec_star_candidate**' da tabela de predição
time -> Campo **date_time** da tabela, porém passado no formato iso e em UTC, no format string
ca -> Campo **closest_approach** na tabela de predição, no formato float
pa -> Campo **position_angle** na tabela de predição, no formato float
vel -> Campo **velocity** na tabela de predição, no formato float
dist -> Campo **delta** na tabela de predição, no formato float
mag -> Campo **g** na tabela de predição, no formato float
longi -> Campo **long** na tabela de predição, no formato float

O campo diameter está para ser adicionado na tabela com a finalização da pagina de detalhes, até lá o raio pode ser passado com valor 0.
