### ISSUE TITLE
Filtro pela região do usuario

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#669]
Adicionar filtro de visibilidade a 'User Selected'

Filtro está na biblioteca **occviz** disponível em occviz.zip
A biblioteca depende das bibliotecas numpy, astropy e scipy.

O instante _date_time_ deve ser passado como str no fomarto 'iso' sem o timestamp de timezone em UTC (timezone 0) ou como um objeto Time() do astropy tbm em formato iso. A maneira mais adequada para fazer isso fica a critério de vocês. 

Como usar a biblioteca:

```python
from occviz import visibility
status, info = visibility(latitude, longitude, radius, date_time, star_coordinates, closest_approach, position_angle, velocity, delta_distance, offset=offset)
``` 
**Formato dos inputs:**
latitude: float
longitude: float
radius: float
instant: string | ex.: '2023-03-22 07:52:50' (a data está em UTC ou timezone 0)
star_coordinates: string | ex.: '23 54 44.9103 +15 53 8.272' | construído como 'ra_star_candidate   dec_star_candidate '
closest_approach: float
position_angle: float
velocity: float
delta_distance: float
offset: tuple or list | ex.: (0,0) ou [0,0] | construído a partir de _off_ra_ e _off_dec_ na forma ```(off_ra, off_dec)``` ou ```[off_ra, off_dec]```

Existe visibilidade quando ```status = True```.

Tasks

- [x] Criar um campo para informar latitude em graus 
       Hover help: 'Latitude in degrees. North is positive, and South is negative.'

- [x] Criar campo para informa longitude
       Hover help: 'Longitude in degrees. East is positive, and West is negative.'

- [x] Criar um campo para infomar o raio da busca em torno do campo. Limitar o raio de busca entre 10 e 5000 com passo de 10. Pode ser equivalente à atual barra 'Diameter'
       Hover help: 'Search radius in Km.'

- [x] Ocultar/Desativar o campo diameter, não temos informação de raio suficiente no momento.
- [x] Exibir a coluna 'C/A Instant' em UTC e atualizar a info para 'Instant of the Closest Approach in UTC".
- [x] Adicionar a exibição da coluna 'C/A' que no banco consta como _closest_approach_, que deve ficar entre 'C/A Instant' e 'P/A' com o header 'C/A', modo visível e hover/help 'Geocentric Closest Approach (arcsec)'

**Comment by rcboufleur** [comment]
[Test_occviz.zip](https://github.com/linea-it/tno/files/12042954/Test_occviz.zip)



[occviz.zip](https://github.com/linea-it/tno/files/12042955/occviz.zip)
