### ISSUE TITLE
Occultation Table

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#681]
A lista de occultações é um componente que se repete em varias telas. 
Para centralizar as demandas deste componente as solicitações vão ficar agrupadas aqui.

**Comment by rcboufleur** [comment]
Segue a tabela descrevendo em que ordem os campos devem aparecer, qual a info de ajuda associada a ele e se ele deverá ficar visível ou invisível por padrão.

Observação 1: os campos **ra_target_deg**, **dec_target_deg** , **ra_star_deg**, **dec_star_deg** devem ser exibidos com 7 ou 8 casas decimais.

Observação 2: A coluna _Object_ usa o modelo **name** (**number**) quando o campo **number** estiver populado, senão exibe apenas **name**.

| Column Name   | Colname in DB | Hover Info / Help text | Default Visibility |
| ----------------   | ---------------- | ------------ | ------------------ |
| Detail               | --     | Occultation Prediction Details  | Visible  |
| Object              | name (number)   | Asteroid Name (Number) |           Visible |
| Number           | number           | Asteroid Number |    Hidden   |
| C/A Instant      | date_time        | Instant of the Closest Approach | Visible |
| P/A                  | position_angle | Position Angle with respect to the star at closest approach (deg) | Visible |
| Velocity           | velocity     | Velocity in the plane of the sky (positive is prograde, negative is retrograde) (Km/s) | Visible|
| Geoc. Distance | delta | Geocentric Distance (AU) | Hidden| 
| Long              | long           | East longitude of sub-planet point (positive towards East) (deg) | Hidden |
| Local Time    | loc_t | Local solar time at sub-planet point (hh:mm) | Hidden |
| RA offset | off_ra | Offset applied to ephemeris in RA (mas) | Hidden |
| DEC offset | off_dec | Offset applied to ephemeris in DEC (mas) | Hidden |
| Proper Motion Status | proper_motion | Status of proper motion correction (Ok/No) | Hidden |
| G mag             | g                      | Star's G magnitude (mag) | Visible |
| J mag              | j                       | Star's J magnitude (mag) | Hidden |
| H mag              | h                       | Star's H magnitude (mag) | Hidden |
| K mag              | k                       | Star's K magnitude (mag) | Hidden |
| Object RA       | ra_target  | Object's Right Ascension (hh mm ss.ssss) | Hidden |
| Object DEC    | dec_target  | Object's Declination (dd mm ss.sss) | Hidden | 
| Object RA (deg) | ra_target_deg | Object's Right Ascension (deg) | Hidden |
| Object DEC (deg) | dec_target_deg | Object's Declination (deg) | Hidden | 
| Star RA            | ra_star_candidate | Star's Right Ascension (hh mm ss.ssss) | Visible |
| Star DEC           | dec_star_candidate | Star's Declination (dd mm ss.sss) | Visible |
| Star RA (deg)    | ra_star_deg | Star's Right Ascension (deg) | Hidden|
| Star DEC (deg)  | dec_star_deg | Star's Declination (deg) | Hidden |
| Star RA unc | e_ra | Star's RA uncertainty (mas) | Hidden |
| Star DEC unc | e_dec | Star's DEC uncertainty (mas) | Hidden |
| Star RA pm | pmra | Star's proper motion in RA (mas/y) | Hidden |
| Star DEC pm | pmdec | Star's proper motion in RA (mas/y) | Hidden |
| Multiplicity Flag | multiplicity_flag | See documentation for details | Hidden |
| CT | ct | Only Gaia DR1 stars used | Hidden |

**Comment by rcboufleur** [comment]
Validado
