### ISSUE TITLE
Review Updates backend_11tech_a54f9b7 frontend_11tech_a54f9b7

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#685]
Review Updates:

Tela: Orbit Trace
- Header "Average Execution Time Asteroid" -> "Ast AET" / info: "Asteroid Average Execution Time"
- Header "Average Execution Time CCD" -> "CCD AET" / info: "CCD Average Execution Time"

Tela: Orbit Trace Details
- "Average Execution Time Asteroid" -> "Asteroid Average Execution Time"
- "Average Execution Time CCD" -> "CCD Average Execution Time"

Tela: Predict Occultation
- Header "Asteroids with Occultations" -> "Ast WO" / info: "Asteroids with Occultations"

Tela: Predict Occultation Details
- "Average Execution Time Asteroid" -> "Asteroid Average Execution Time"

Tela: Pública
- Header "Detail": deixar o header em branco para reduzir a largura da coluna para apenas o (i)
- Botão (i): tranformar em link para abrir a página de detalhe em nova janela
- Definir limite superior de magnitude padrão para 14
- Mudar header "Occultation Result - Total: $val" -> "Total Occultation Predictions: $val"

- Adicionar botão para limpar o filtro em User Selected (mas isso pode aguardar a integração do filtro por localização que eu devo enviar o código essa semana)

**Comment by glaubervila** [comment]
Validado por mim pode ser marcado como Done.
