### ISSUE TITLE
Modificações na landing page do DB de predições públicas

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#698]
- [x] Corrigir o título da página para Occultation Prediction Database e mover para o header.
- [x] Mover a explicação atualmente abaixo do texto para a caixa no header.
- [x] Reorganizar as abas para **HOME ABOUT DOCUMENTATION CONTACT**.
- [x] Substituir os caminhos: tutorials e occultation > contact e documentation
- [x] Deixar somente “All events” e “User Selected” como opções na tabela de filtragem, sendo “All events” o primeiro item.
- [x] Adicionar "Powered by LIneA" no footer.

**Comment by jandsonrj** [comment]
Task completed.
