### ISSUE TITLE
Modificações estruturais na página de predições de ocultações públicas

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#699]
- [x] ~Separar da página pública do portal TNO.~
- [x] ~Requerer URL exclusiva para esta página pública.~
- [x] Indicar a que período se refere o número total de ocultações exibidos na tabela.
- [x] ~Indicar na landing page a data da última atualização/execução de predições da tabela. Hoje existe um ‘last updated’ que não está relacionado a isso.~ Exibir na lista de eventos a data de atualização de cada evento.

**Comment by glaubervila** [comment]
@rcboufleur Acredito que não é possivel mostrar a data da ultima atualização da tabela inteira de predições. Por que essa data não existe, a tabela é incremental.
Exemplo:  
Uma atualização hoje para uma classe de objeto centaurs mudaria a data de atualização como a tabela tendo sido atualizada hoje, mas na realidade só os eventos referentes aos centauros é que foram atualizados. 

Minha Sugestão é que seja exibido na lista a data de atualização de cada evento. 
Essa informação já existe só não é apresentada na lista.
