### ISSUE TITLE
Criar layout para a exibição dos highlights da predição

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#726]
Primeiro card contendo: count, unique asteroids, erarliest, latest
Segundo card contendo: Today count, Week Count, Next Week Count
Terceiro card contendo: Month count, Next Month Count

{
    "count": 79357,
    "earliest": "2023-08-01T03:00:20+00:00",
    "latest": "2024-06-29T02:43:36+00:00",
    "unique_asteroids": 2204,
    "today_count": 563,
    "today_already_have_map": 51,
    "total_maps_size": 3436839,
    "week_count": 3838,
    "next_week_count": 3718,
    "month_count": 16036,
    "next_month_count": 14046
}

**Comment by glaubervila** [comment]
@jandsonrj O Endpoint para consulta é este: 
http://localhost/api/occultations/highlights/
