### ISSUE TITLE
Adicionar o cálculo dos paths após a predição

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#759]
Atualmente os paths são calculados por um serviço a partir da tabela de predições. Esse procedimento agora será executado na pipeline, quando um evento de predição for encontrado.

**Comment by glaubervila** [comment]
@rcboufleur Atualizei o pipeline, adicionei as funções para calcular o path e fazer o registro na tabela de predições. 

A solução atual ficou com 2 problemas a serem resolvidos no futuro. 
- Existe o download de arquivos de dependencia do astropy que ocorre durante o processamento. 
- O calculo dos paths está sendo executado na etapa final do pipeline na função de registro das predições, não é o local adequado por se tratar de uma etapa que é executada de forma sequencial. o melhor local seria logo apos a execução do praia_occ.
