### ISSUE TITLE
Refatoração do formulário de submissão de jobs de predições de ocultações 

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#768]
A refatoração do formulário de submissão de jobs de predições de ocultações melhorará a compreensão e organização do código. Nâo é urgente, porém é importante para manutenção futura do Portal.

**OBS:**  @glaubervila 26/02/2024
 Acabou ficando importante, existem bugs no formulário devido utilização de lib antiga. está prejudicando o funcionando do build da imagem de frontend.

**Comment by glaubervila** [comment]
Closed in #885
