### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by gschwend** [linea-it/tno#929]
```[tasklist]
### Preparação, antes de iniciar a implementação no código fonte.
- [x] Pedir ao helpdesk acesso administrativo no Google Analytics do LIneA.
- [x] Adicionar a propriedade GA4 - TNO, que vai gerar um ID para colocar no código fonte.
- [x] Instalar a biblioteca react-ga4
- [x] Definir em quais requisições o GA vai ser chamado @rcboufleur
```

> ### Requisitos para a coleta do GA @jandsonrj 
> A) até o lançamento:
> - coleta padrão do google analytics
> 
> B) se possivel ate o lançamento
> - coleta do disparo de geração de mapa (quando clica em evento que não tem mapa, ajuda a estimar com que frequencia precisamos criar mapas que nao existem)
> - coleta de valor do filtro em magnitude (para saber qual o limite em magnitude que normalmente as pessoas usam, ajuda a configurar melhor outros serviços como a pré geração de mapas)
> - coleta de tipo de filtro utilizado (para saber se há mais interesse em classes e subclasses ou objetos específicos)
> - coleta de requisição usando o geofiltro (saber a frequencia de uso para estimar o custo de processamento)
> - coleta se usou tela de table ou card

**Comment by gschwend** [comment]
@jandsonrj esse issue está concluído?

**Comment by jandsonrj** [comment]
> @jandsonrj esse issue está concluído?

Ainda não, falta adicionar os requisitos feito pelo Rodrigo
